config/routes.rb
Pigly::Application.routes.draw do
  root to: "pigly#index"
  get "logout", :to => "sessions#destroy", as: "logout"
  get "error", :to => "restaurants#error", as: "error"
  get "facebook", :to => "sessions#facebook", as: "facebook"
  get "friends", :to => "sessions#friends", as: "friends"
  resources :users, only: [:show, :new, :edit, :create, :update]
  resources :sessions, only: [:create, :new, :destroy]
  resources :restaurants do
    post 'search', on: :collection, as: "search"
    resources :items do
    end
  end

  resources :votes, only: :create

end

app/controllers/pigly_controller.rb
class PiglyController < ApplicationController

  def index # homepage
    @restaurant = Restaurant.new
    @names = Restaurant.all.map(&:name)
  end

end

app/views/pigly/index.html.erb
<div class='main_search'>
  <div><%= image_tag "Pigly-logo.png", :class => "main_logo" %></div>
  </br>
  <%= form_for @restaurant, url: search_restaurants_path do |restaurant_form| %>
    <%= restaurant_form.text_field :name, :placeholder => "Search For A Restaurant..." %>
  <% end %>
  <% if flash[:notice] %>
    <div id="front-page-notice"><%= flash[:notice] %></div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('.tab').hide();
  });
  $(function() {
    var restaurant_names = <%= raw @names %>;
    var searchBox = $('#restaurant_name');
    searchBox.autocomplete({
      source: restaurant_names,

      select: function(e, ui) {
        if (event.type == 'click') {
         $(e.target).val(event.target.innerHTML); 
        }
        $(e.target).parents("form").submit();
      }
    });
  });
 </script>